// src/components/AvatarList/item.vue
<template>
  <a-tooltip :title="tips">
    <a-avatar :size="size" :src="src" :style="!src && excessItemsStyle">
      <slot></slot>
    </a-avatar>
  </a-tooltip>
</template>

<script>
export default {
  name: "AvatarListItem",
  props: {
    tips: {
      type: String,
      default: ""
    },
    src: {
      type: String,
      default: ""
    }
  },
  data() {
    return {
      size: this.$parent.size,
      excessItemsStyle: this.$parent.excessItemsStyle
    };
  },
  watch: {
    "$parent.size"(val) {
      this.size = val;
    },
    "$parent.excessItemsStyle"(val) {
      this.excessItemsStyle = val;
    }
  }
};
</script>

// src/components/AvatarList/Item.jsx
import PropTypes from 'ant-design-vue/es/_util/vue-types'
import { Tooltip, Avatar } from 'ant-design-vue'
import { getSlotOptions } from 'ant-design-vue/lib/_util/props-util'
import { warning } from 'ant-design-vue/lib/vc-util/warning'

export const AvatarListItemProps = {
  tips: PropTypes.string.def(null),
  src: PropTypes.string.def('')
}

const Item = {
  __ANT_AVATAR_CHILDREN: true,
  name: 'AvatarListItem',
  props: AvatarListItemProps,
  created () {
    warning(getSlotOptions(this.$parent).__ANT_AVATAR_LIST, 'AvatarListItem must be a subcomponent of AvatarList')
  },
  render () {
    const AvatarDom = <Avatar size={this.$parent.size} src={this.src} />
    return this.tips && <Tooltip title={this.tips}>{AvatarDom}</Tooltip> || <AvatarDom />
  }
}

export default Item
