// src/components/AvatarList/Item.vue
<template>
  <li :class="[prefixCls, size]">
    <slot>
      <tooltip>
        <template slot="title">{{ tips }}</template>
        <avatar :size="size !== 'mini' && size || 20" :src="src" />
      </tooltip>
    </slot>
  </li>
</template>

<script>
  import Avatar from 'ant-design-vue/es/avatar'
  import Tooltip from 'ant-design-vue/es/tooltip'

  export default {
    name: "AvatarItem",
    components: {
      Avatar,
      Tooltip
    },
    props: {
      prefixCls: {
        type: String,
        default: 'ant-pro-avatar-list-item'
      },
      tips: {
        type: String,
        default: '',
        required: false
      },
      src: {
        type: String,
        default: ''
      }
    },
    data () {
      return {
        size: this.$parent.size
      }
    },
    watch: {
      '$parent.size' (val) {
        this.size = val
      }
    }
  }
</script>

// src/components/AvatarList/Item.jsx
import PropTypes from 'ant-design-vue/es/_util/vue-types'
import { Tooltip, Avatar } from 'ant-design-vue'
import { getSlotOptions } from 'ant-design-vue/lib/_util/props-util'
import { warning } from 'ant-design-vue/lib/vc-util/warning'

export const AvatarListItemProps = {
  tips: PropTypes.string,
  src: PropTypes.string.def('')
}

const Item = {
  __ANT_AVATAR_CHILDREN: true,
  name: 'AvatarListItem',
  props: AvatarListItemProps,
  created () {
    warning(getSlotOptions(this.$parent).__ANT_AVATAR_LIST, 'AvatarListItem must be a subcomponent of AvatarList')
  },
  render () {
    const size = this.$parent.size === 'mini' ? 'small' : this.$parent.size
    const AvatarDom = <Avatar size={size || 'small'} src={this.src} />
    return (this.tips && <Tooltip title={this.tips}>{AvatarDom}</Tooltip>) || <AvatarDom />
  }
}

export default Item
